# **Introduction Python**

Authors: [Ali El Hadi Ismail Fawaz](https://hadifawaz1999.github.io) and [Germain Forestier](https://germain-forestier.info/)

## **Data Types ion Python**

- `int`: integer number (ex: 1, 2, -1, 0 etc.)
- `float`: real number (ex: 0.123, $\sqrt{2}$ etc.)
- `str`: string of text (ex: 'Ali', 'Hello World' etc.)
- `bool`: boolean value (ex: True, False)

To know the type of anything in python, use the `type()` function.

## **Mathematical operations in Python**

- `+` addition
- `-` subtraction
- `*` multiplication
- `/` division
- `**` exponent

In [ ]:
tall = True # assignment

height = 1.79
print(type(height))
weight = 68.7

bmi = weight / height ** 2 # the ** means to the power .

print(bmi) # print() allows to print to the standard output

<class 'float'>
21.44127836209856

### **Exercise 1**: Handling math oprtations

- Create a variable `speed` of value `3.12` (km/h)
- Create a variable `time_spent` of value `10.4` (h)
- Find the total distance in meters traveled in time_spent hours.
- Print the results

In [ ]:
# initialize the speed variable

# initialize the time_spent variable

# calculate the distance in meters traveled in time_spent hours

# Print the results

 ### Solution - Exercise 1

In [ ]:
speed = 3.12

time_spent = 10.4

distance_in_km = speed * time_spent
distance_in_m = distance_in_km * (10 ** 3)

print(distance_in_km)

### **Exercise 2**: Float - String conversion

- Execute the following code
- Correct the mistake, hint: use the `str()` function
- Convert the `pi_string` variable to type float, store the float value in a new variable called `pi_float`

In [ ]:
# Definition of speed and getting distance
speed = 3.12
time_spent = 10.4
distance_in_km = speed * time_spent

# Fix the following two lines
print("My car was running today at a speed of " + speed + " km/h for "+ time_spent + "hours.")
print("This means the car ran a distance of " + distance_in_km + " km.")

# Convert pi_string to float
pi_string = '3.1415926'

# Print the results of pi_float

 ### Solution - Exercise 2

In [ ]:
# Definition of speed and getting distance
speed = 3.12
time_spent = 10.4
distance_in_km = speed * time_spent

# Fix the following two lines
print("My car was running today at a speed of " + str(speed) + " km/h for "+ str(time_spent) + "hours.")
print("This means the car ran a distance of " + str(distance_in_km) + " km.")

# Convert pi_string to float
pi_string = '3.1415926'
pi_float = float(pi_string)

# Print the results of pi_float
print(pi_float, type(pi_float))

### **Exercise 3**: Find the error

Which one of these Python instruction will produce an error ?

1. `"I can add integers, like " + str(5) + " to strings."`
2. `"I said " + ("Hey " * 2) + "Hey!"`
3. `"The correct answer to this multiple choice exercise is answer number "+2`
4. `True + False`

 ### Solution - Exercise 3

3.

## Lists in Python

Example of a list

In [ ]:
my_list = [13, 18, 22, 20]

- Allows to store multiple values into one varibale
- Allows to store multiple values of different types

Example of a list containing the name followed by the age of a person

In [ ]:
my_list = ['Marc', 21, 'Sara', 29, 'Julien', 23]

- It is also possible to define a nested list (list of lists)

In [ ]:
my_list = [['Marc', 21],
           ['Sara', 29],
           ['Julien', 23]]

### **Exercise 4**: Define and Print a list

Define a list containing the height of different people, store it in a variable called `heights`, print this list using the `print()` function

In [ ]:
# Heights of different people in cm

person1 = 192.3
person2 = 165.2
person3 = 189.0
person4 = 175.21

# Define the list and store it in a variable called heights

# Print the list

 ### Solution - Exercise 4

In [ ]:
# Heights of different people in cm

person1 = 192.3
person2 = 165.2
person3 = 189.0
person4 = 175.21

# Define the list and store it in a variable called heights
heights = [person1, person2, person3, person4]

# Print the list
print(heights)

### **Exercise 5**: Define a nested list

Define a nested list (list of lists) where each sub-list is made of 2 elements, a person's name and their height. Put this nested list in a variable called `names_heights`. Use the heights values from the previous exericise and use the names of your choosing.

In [ ]:
# Write your code here (print the results)

 ### Solution - Exercise 5

In [ ]:
person1_height = 192.3
person2_height = 165.2
person3_height = 189.0
person4_height = 175.21

person1_name = 'Marc'
person2_name = 'Julien'
person3_name = 'Sara'
person4_name = 'Marie'

names_heights = [[person1_name, person1_height],
                 [person2_name, person2_height],
                 [person3_name, person3_height],
                 [person4_name, person4_height]]

print(names_heights)

### **Exercise 6**: Find the correct list initialization

Which of these list initializations is valid in Python ?

1. `my_list = [1, 2, 3, 4]`
2. `my_list = [[1, 2, 3], [4, 5, 6]]`
3. `my_list = [1, 'test', 2.4]`
4. `my_list = [1, 2, 'test' * 4, 4.2]`

 ### Solution - Exercise 6

1, 2, 3, 4

## **List Manipulation in Python**

- Retrieving an element from a list by indexing

In [ ]:
my_list = [1, 'house', 2.3, 'Marc', 3, 5, 'dad']

print(my_list[0]) # get first element counting forward
print(my_list[1]) # get second element counting forward

print(my_list[-1]) # get first element counting backwards
print(my_list[-2]) # get second element counting backwards

1
house
dad
5

- Retrieving a set of elements from a list using `:` (slicing)

In [ ]:
my_list = [1, 'house', 2.3, 'Marc', 3, 5, 'dad']

print(my_list[1:3]) # get the second and third element, exclude the forth

['house', 2.3]

- Use slicing by only setting the beginning or end

In [ ]:
my_list = [1, 'house', 2.3, 'Marc', 3, 5, 'dad']

print(my_list[:3]) # get all elements from the start until index 2, exclude index 3
print(my_list[3:]) # get all elements from index 3 (included) till the end of the list

[1, 'house', 2.3]
['Marc', 3, 5, 'dad']

### **Exercise 7**: Indexing a list

- Given a list containing the name of a person and their height, find the average height of these three people `Marc`, `Julien` and `Marie`, put the results in a variable called `average`.
- Print the value of `average`

In [ ]:
names_heights = ['Marc', 187.2, 'Ali', 192.1, 'Marie', 178.2, 'Steve', 165.4, 'Julien', 170.3]

# store the average height of Marc, Julien and Marie in a variable called average

# print the results

 ### Solution - Exercise 7

In [ ]:
names_heights = ['Marc', 187.2, 'Ali', 192.1, 'Marie', 178.2, 'Steve', 165.4, 'Julien', 170.3]

# store the average height of Marc, Julien and Marie in a variable called average

average = (names_heights[1] + names_heights[5] + names_heights[9]) / 3.0

# print the results

print(average)

### **Exercise 8**: Slicing list

- Define a list called `front` containing the information from `names_heights` of the 3 first people
- Define a list called `back` containing the information from `names_heights` of the 2 last people
- Print the 2 lists

In [ ]:
names_heights = ['Marc', 187.2, 'Ali', 192.1, 'Marie', 178.2, 'Steve', 165.4, 'Julien', 170.3]

# Define the list front
# Define the list back

# print the 2 lists

 ### Solution - Exercise 8

In [ ]:
names_heights = ['Marc', 187.2, 'Ali', 192.1, 'Marie', 178.2, 'Steve', 165.4, 'Julien', 170.3]

# Define the list front
front = names_heights[:6]
# Define the list back
back = names_heights[6:]

# print the 2 lists

print(front)
print(back)

### **Exercise 9**: Find the correct answer - 2D list indexing

- What is the outcome of `names_heights_2d[-1][1]`

In [ ]:
names_heights = [['Marc', 187.2],
                 ['Ali', 192.1],
                 ['Marie', 178.2],
                 ['Steve', 165.4],
                 ['Julien', 170.3]]

1. A float, the height of `Marie`
2. A string `Steve`
3. A float, the height of `Julien`
4. A string, `Marc`

 ### Solution - Exercise 9

3.

### **Change elements in a list**

In [ ]:
names_heights = ['Marc', 187.2, 'Ali', 192.1, 'Marie', 178.2, 'Steve', 165.4, 'Julien', 170.3]

print(names_heights)
print()

# Change one element
names_heights[0] = 'Mireille'
print(names_heights)
print()

# Change one element and its type as well
names_heights[0] = True
print(names_heights)
print()

# Change a consecutive sub-list
names_heights[2:4] = ['Jad', 189.3]
print(names_heights)
print()

['Marc', 187.2, 'Ali', 192.1, 'Marie', 178.2, 'Steve', 165.4, 'Julien', 170.3]

['Mireille', 187.2, 'Ali', 192.1, 'Marie', 178.2, 'Steve', 165.4, 'Julien', 170.3]

[True, 187.2, 'Ali', 192.1, 'Marie', 178.2, 'Steve', 165.4, 'Julien', 170.3]

[True, 187.2, 'Jad', 189.3, 'Marie', 178.2, 'Steve', 165.4, 'Julien', 170.3]

### **Add and remove elements from a list**

In [ ]:
names_heights = ['Marc', 187.2, 'Ali', 192.1, 'Marie', 178.2, 'Steve', 165.4, 'Julien', 170.3]

print(names_heights)
print()

names_heights = names_heights + ['Jad', 189.2] # adding new elements

print(names_heights)
print()

del(names_heights[0]) # delete the first element

print(names_heights)
print()

del(names_heights[0]) # delete the first element

print(names_heights)
print()

['Marc', 187.2, 'Ali', 192.1, 'Marie', 178.2, 'Steve', 165.4, 'Julien', 170.3]

['Marc', 187.2, 'Ali', 192.1, 'Marie', 178.2, 'Steve', 165.4, 'Julien', 170.3, 'Jad', 189.2]

[187.2, 'Ali', 192.1, 'Marie', 178.2, 'Steve', 165.4, 'Julien', 170.3, 'Jad', 189.2]

['Ali', 192.1, 'Marie', 178.2, 'Steve', 165.4, 'Julien', 170.3, 'Jad', 189.2]

### **Exercise 10**: Adding to a list and storing it a new list

- Add a new person to `names_heights` named `Alice` of height `180.2` and store it a new list called `names_heights_1`
- Add a new person to `names_heights_1` named `Bob` of height `160.1` and store it a new list called `names_heights_2`
- print both new lists

In [ ]:
names_heights = ['Marc', 187.2, 'Ali', 192.1, 'Marie', 178.2, 'Steve', 165.4, 'Julien', 170.3]

# Add Alice and store in names_heights_1

# Add Bob and store in names_heights_2

# print both new lists

 ### Solution - Exercise 10

In [ ]:
names_heights = ['Marc', 187.2, 'Ali', 192.1, 'Marie', 178.2, 'Steve', 165.4, 'Julien', 170.3]

# Add Alice and store in names_heights_1
names_heights_1 = names_heights + ['Alice', 180.2]

# Add Bob and store in names_heights_2
names_heights_2 = names_heights_1 + ['Bob', 160.1]

# print both new lists

print(names_heights_1)
print(names_heights_2)

### **Exercise 11**: Find the correct answer - Deleting from 2d list

Which of the following instruction deletes the information of `Marc` ?

In [ ]:
names_heights = [['Marc', 187.2],
                 ['Ali', 192.1],
                 ['Marie', 178.2],
                 ['Steve', 165.4],
                 ['Julien', 170.3]]

1. `del(names_heights[-1][1])`
1. `del(names_heights[1])`
1. `del(names_heights[2][0])`
1. `del(names_heights[0])`

 ### Solution - Exercise 11

4.

## **Functions in Python**

In [ ]:
fam = [1.73, 1.68, 1.71, 1.89]
print(fam)

tallest = max(fam)
print(tallest)

print(round(1.68, 1))
help(round)

[1.73, 1.68, 1.71, 1.89]
1.89
1.7
Help on built-in function round in module builtins:

round(number, ndigits=None)
    Round a number to a given precision in decimal digits.

    The return value is an integer if ndigits is omitted or None.  Otherwise
    the return value has the same type as the number.  ndigits may be negative.

### **Exercise 12**: Intro to functions

- Use the function `print()` to show the content of `my_list`
- Use the function `type()` to show the type of `my_list`
- Use the function `len()` to get the length of `my_list` and print it
- Use the casting function `int()` to transform `my_bool` to an integer and print it

In [ ]:
my_list = [1, 2, 3, 4]
my_bool = True

# print the content of my_list
# print the type of my_list
# print the length of my_list

# print the integer version of my_bool

 ### Solution - Exercise 12

In [ ]:
my_list = [1, 2, 3, 4]
my_bool = True

# print the content of my_list
print(my_list)
# print the type of my_list
print(type(my_list))
# print the length of my_list
print(len(my_list))

# print the integer version of my_bool
print(int(my_bool))

### **Exercise 13**: Arguments - Sort list

- Use the `+` operation to concatenate `list1` and `list2`
- Store the concenated lists in `my_list`
- Sort `my_list` in descending order using `sorted()` and by specifying the argument `reverse` to be `True`
- Store the sorted list in `sorted_list`
- Print the sorted list

In [ ]:
list1 = [1.2, 3.2, 1.3]
list2 = [4.25, 2.1, -1.3]

# concetante list1 and list2: store results in my_list

# sort my_list in descending order: store results in sorted_list

# prtin sorted list

 ### Solution - Exercise 13

In [1]:
list1 = [1.2, 3.2, 1.3]
list2 = [4.25, 2.1, -1.3]

# concetante list1 and list2: store results in my_list

my_list = list1 + list2

# sort my_list in descending order: store results in sorted_list

sorted_list = sorted(my_list, reverse=True)

# prtin sorted list

print(sorted_list)

[4.25, 3.2, 2.1, 1.3, 1.2, -1.3]

## **Methods on lists and strings**

In [ ]:
my_list = ['Marie', 22, 'Marc', 18, 'Mom', 45, 'Dad', 49]
print(my_list)

print(my_list.index('Mom')) # get index of element 'Mom'
print(my_list.count(22)) # get number of occurences of element 22

['Marie', 22, 'Marc', 18, 'Mom', 45, 'Dad', 49]
4
1

In [ ]:
my_string = 'marie'
print(my_string)

print(my_string.capitalize()) # transform the first letter to capital
print(my_string.replace('ie','y')) # replace a part of the string with another string

marie
Marie
mary

### **Exercise 14**: Manipulating strings

- Use the method `upper()` on `my_string` and store the output in `my_upper_string`
- Print the two strings
- Get the number of occurence of the letter `o` in both strings and print both outputs

In [ ]:
my_string = "book"

# define my_upper_string using upper()

# print both strings

# get number of occurences of letter `o` in both strings

# count these 2 numbers

 ### Solution - Exercise 14

In [ ]:
my_string = "book"

# define my_upper_string using upper()
my_upper_string = my_string.upper()

# print both strings
print(my_string, my_upper_string)

# get number of occurences of letter `o` in both strings

o_my_string = my_string.count('o')
o_my_upper_string = my_upper_string.count('o')

# count these 2 numbers

print(o_my_string, o_my_upper_string)

### **Exercise 15**: Manipulation of lists: append and reverse

- Use the `append()` method on `my_list` twice to add respectively the elements `Jad` and `24` at the end of the list
- print the list now
- Use the `reverse()` method to reverse the elements of `my_list`, this function won't return anything, it changes the actual list
- Print the reversed list

In [ ]:
my_list = ['Marie', 22, 'Marc', 18, 'Mom', 45, 'Dad', 49]

# append the two elements `Jad` and `24`

# print the list now

# use `reverse()` to reverse the elements

# print the new list

 ### Solution - Exercise 15

In [ ]:
my_list = ['Marie', 22, 'Marc', 18, 'Mom', 45, 'Dad', 49]

# append the two elements `Jad` and `24`
my_list.append('Jad')
my_list.append(24)

# print the list now

print(my_list)

# use `reverse()` to reverse the elements

my_list.reverse()

# print the new list

print(my_list)

## **Packages in Python**

- A set of python scripts
- Specific functions, data types and methods
- 1000s of pacakges exist (numpy, matplotlib, scikit-learn etc.)

In [ ]:
import numpy
numpy.array([1, 2, 3])

import numpy as np
np.array([1, 2, 3])

from numpy import array
array([1, 2, 3])

array([1, 2, 3])

### **Exercise 16**: The `math` package

- import the `math` package
- Calculate the circumference and surface of a circle using radius `r=0.43`
- Hint: Use `math.pi`

In [ ]:
# Definition of radius
r = 0.43

# Import the math package

# Calculate C
C = 0

# Calculate A
A = 0

# Build printout
print("Circumference: " + str(C))
print("Area: " + str(A))

 ### Solution - Exercise 16

In [ ]:
# Definition of radius
r = 0.43

# Import the math package
import math

# Calculate C
C = 2 * math.pi * r

# Calculate A
A = math.pi * (r ** 2)

# Build printout
print("Circumference: " + str(C))
print("Area: " + str(A))

### **Exercise 17**: Handling angles with `math`

- Import only the function `radians` from the `math` package
- Calculate the distance traveled by the moon on its orbit over `12 degrees`
- Hint: use `radious * angle` where `angle` should be in radious
- Store the value is `dist`
- Use `radians()` to convert the angle from degree to radians
- Print `dist`

In [ ]:
# Definition of radius
r = 192500

# Import radians function of math package

# Travel distance of Moon over 12 degrees. Store in dist.

# Print out dist

 ### Solution - Exercise 16

In [ ]:
# Definition of radius
r = 192500

# Import radians function of math package
from math import radians

# Travel distance of Moon over 12 degrees. Store in dist.
dist = r * radians(12)

# Print out dist
print(dist)

40317.10572106901

### **Numpy**

- Numerical Python
- Alternative to Python list: numpy array
- Faciliates the work on arrays
- A lot more efficient for calculations

**Example: Vectorization**:

In [ ]:
import numpy as np

np_height = np.array([ 1.73, 1.68, 1.71, 1.89, 1.79])
print(np_height)

np_weight = np.array([ 65.4, 59.2, 63.6, 88.4, 68.7])
print(np_weight)

bmi = np_weight / np_height ** 2
print(bmi)

[1.73 1.68 1.71 1.89 1.79]
[65.4 59.2 63.6 88.4 68.7]
[21.85171573 20.97505669 21.75028214 24.7473475  21.44127836]

A less efficient approach to code the above code, is to calculate the bmi individually for each element.

- A numpy array can only contain one single type
- The `+` operation is a literal element wise addition

In [ ]:
array = np.array([1.0, "is", True])
print(array)

python_list = [1, 2, 3]
numpy_array = np.array([1, 2, 3])

print(python_list + python_list)
print(numpy_array + numpy_array)

['1.0' 'is' 'True']
[1, 2, 3, 1, 2, 3]
[2 4 6]

**Indexing and Selection in numpy array**

In [ ]:
import numpy as np

bmi = np.array([21.8, 20.9, 21.7, 24.7, 21.4])

print(bmi)
print(bmi[1])
print(bmi > 23)
print(bmi[bmi > 23])

[21.8 20.9 21.7 24.7 21.4]
20.9
[False False False  True False]
[24.7]

### **Exercise 17**: Create a numpy array

- Import the package `numpy` as the allias `np`
- Create the numpy array `my_np` using the list `my_list`
- print the types of `my_list` and `my_np` to make sure they are different

In [ ]:
my_list = [180, 215, 210, 210, 188, 176, 209, 200]

# Import the numpy package as np

# Create a numpy array from my_list: my_np

# Print out types of my_list and my_np

 ### Solution - Exercise 17

In [ ]:
my_list = [180, 215, 210, 210, 188, 176, 209, 200]

# Import the numpy package as np
import numpy as np

# Create a numpy array from my_list: my_np
my_np = np.array(my_list)

# Print out types of my_list and my_np
print(type(my_list))
print(type(my_np))

### **Exercise 18**: The baseball data

- Create a numpy array `np_height` containing the `height` values (that are in inches) and print it
- Rescale `np_height` to values in meters by multipying it by `0.0254` and store them in `np_height_m`
- print the `np_height_m`

In [ ]:
# download the baseball data
!wget -nc https://germain-forestier.info/dataset/baseballdata.py

import numpy as np

from baseballdata import hieght

# Create a numpy array from height: np_height

# Print out np_height

# Convert np_height to m: np_height_m

# Print np_height_m

 ### Solution - Exercise 18

In [ ]:
# download the baseball data
!wget -nc https://germain-forestier.info/dataset/baseballdata.py

import numpy as np

from baseballdata import height

# Create a numpy array from height: np_height
np_height = np.array(height)

# Print out np_height
print(np_height)

# Convert np_height to m: np_height_m
np_height_m = 0.0254 * np_height

# Print np_height_m
print(np_height_m)

File ‘baseballdata.py’ already there; not retrieving.

[74 74 72 ... 75 75 73]
[1.8796 1.8796 1.8288 ... 1.905  1.905  1.8542]

### **Exercise 19**: BMI of baseball players

- Load the `weight` values and store them in a numpy array called `np_weight` (values are in pounds)
- Convert the values to kilogram and store them in `np_weight_kg` (multiple the values by `0.453592`)
- Use both `np_height_m` and `np_weight_kg` to calculate the `BMI` for each of the baseball players: $BMI = \dfrac{weight(kg)}{height(m)^2}$ and store them in an array `np_bmi`
- print the `np_bmi`

In [ ]:
# download the baseball data
!wget -nc https://germain-forestier.info/dataset/baseballdata.py

# height and weight are available as a regular lists
from baseballdata import height, weight

# Import numpy
import numpy as np

# Create array from height with correct units: np_height_m
np_height_m = np.array(height) * 0.0254

# Create array from weight with correct units: np_weight_kg

# Calculate the BMI: np_bmi

# Print out np_bmi

 ### Solution - Exercise 19

In [ ]:
# download the baseball data
!wget -nc https://germain-forestier.info/dataset/baseballdata.py

# height and weight are available as a regular lists
from baseballdata import height, weight

# Import numpy
import numpy as np

# Create array from height with correct units: np_height_m
np_height_m = np.array(height) * 0.0254

# Create array from weight with correct units: np_weight_kg
np_weight_kg = np.array(weight) * 0.453592

# Calculate the BMI: np_bmi
np_bmi = np_weight_kg / (np_height_m) ** 2

# Print out np_bmi
print(np_bmi)

File ‘baseballdata.py’ already there; not retrieving.

[23.11037639 27.60406069 28.48080465 ... 25.62295933 23.74810865
 25.72686361]

### **Exercise 20**: Selecting BMIs

- Define the boolean array `light` that containes `True` value when the index corresponds to a BMI less than 21 (at the same index in thr `np_bmi` array), and `False` otherwise (`light` and `np_bmi` have the same length)
- Print `light` array
- Print the BMI values less than 21

In [ ]:
# download the baseball data
!wget -nc https://germain-forestier.info/dataset/baseballdata.py

# height and weight are available as a regular lists
from baseballdata import height, weight

# Import numpy
import numpy as np

# Calculate the BMI: bmi
np_height_m = np.array(height) * 0.0254
np_weight_kg = np.array(weight) * 0.453592
np_bmi = np_weight_kg / np_height_m ** 2

# Create the light array

# Print out light

# Print out BMIs of all baseball players whose BMI is below 21

 ### Solution - Exercise 20

In [ ]:
# download the baseball data
!wget -nc https://germain-forestier.info/dataset/baseballdata.py

# height and weight are available as a regular lists
from baseballdata import height, weight

# Import numpy
import numpy as np

# Calculate the BMI: bmi
np_height_m = np.array(height) * 0.0254
np_weight_kg = np.array(weight) * 0.453592
np_bmi = np_weight_kg / np_height_m ** 2

# Create the light array
light = np_bmi < 21

# Print out light
print(light)

# Print out BMIs of all baseball players whose BMI is below 21
print(np_bmi[light])

File ‘baseballdata.py’ already there; not retrieving.

[False False False ... False False False]
[20.54255679 20.54255679 20.69282047 20.69282047 20.34343189 20.34343189
 20.69282047 20.15883472 19.4984471  20.69282047 20.9205219 ]

### **Exercise 21**: Same outcome

Whcih line of code produces the same output as this following line:

`np.array([True, 1, 2]) + np.array([3, 4, False])`

1. `np.array([True, 1, 2, 3, 4, False])`
2. `np.array([4, 3, 0]) + np.array([0, 2, 2])`
3. `np.array([1, 1, 2]) + np.array([3, 4, -1])`
4. `np.array([0, 1, 2, 3, 4, 5])`

 ### Solution - Exercise 21

2.

### **Exercise 22**: Silicing baseball arrays

- Print the 50th element of the `np_height` array
- Print the sub-array of `np_weight` containing the 100th to 110th element (included)

In [ ]:
# download the baseball data
!wget -nc https://germain-forestier.info/dataset/baseballdata.py

# height and weight are available as a regular lists
from baseballdata import *

# Import numpy
import numpy as np

# Store weight and height lists as numpy arrays
np_weight = np.array(weight)
np_height = np.array(height)

# Print out the weight of the 50th player

# Print out sub-array of np_height: 100th to 110th player (included)

 ### Solution - Exercise 22

In [ ]:
# download the baseball data
!wget -nc https://germain-forestier.info/dataset/baseballdata.py

# height and weight are available as a regular lists
from baseballdata import *

# Import numpy
import numpy as np

# Store weight and height lists as numpy arrays
np_weight = np.array(weight)
np_height = np.array(height)

# Print out the height of the 50th player
print(np_height[49])

# Print out sub-array of np_weight: 100th to 110th player (included)
print(np_weight[99:110])

File ‘baseballdata.py’ already there; not retrieving.

70
[195 220 230 180 220 180 180 170 210 215 200]

### **2D Numpy array**

- Creation of a 2D numpy array

In [ ]:
import numpy as np

np_2d = np.array([[1.73, 1.68, 1.71, 1.89, 1.79],
                  [65.4, 59.2, 63.6, 88.4, 68.7]])

print(np_2d)
print(np_2d.shape)

[[ 1.73  1.68  1.71  1.89  1.79]
 [65.4  59.2  63.6  88.4  68.7 ]]
(2, 5)

- Indexing over a 2D numpy array

In [ ]:
import numpy as np

np_2d = np.array([[1.73, 1.68, 1.71, 1.89, 1.79],
                  [65.4, 59.2, 63.6, 88.4, 68.7]])

print(np_2d[0])
print(np_2d[0][2])
print(np_2d[0,2])
print(np_2d[:,1:3])
print(np_2d[1,:])

[1.73 1.68 1.71 1.89 1.79]
1.71
1.71
[[ 1.68  1.71]
 [59.2  63.6 ]]
[65.4 59.2 63.6 88.4 68.7]

- Get the shape of the array

In [ ]:
import numpy as np

np_2d = np.array([[1.73, 1.68, 1.71, 1.89, 1.79],
                  [65.4, 59.2, 63.6, 88.4, 68.7]])

print(np_2d.shape)

(2, 5)

### **Exercise 23**: 2D baseball

- Define the array `np_baseball` using the values in `baseball`
- Print the type and shape of `np_baseball`

In [ ]:
# download the baseball data
!wget -nc https://germain-forestier.info/dataset/baseballdata.py

# baseball is available as a regular list of lists
from baseballdata import baseball

# Import numpy package
import numpy as np

# Create a 2D numpy array from baseball: np_baseball

# Print out the type and shape of np_baseball

 ### Solution - Exercise 23

In [ ]:
# download the baseball data
!wget -nc https://germain-forestier.info/dataset/baseballdata.py

# baseball is available as a regular list of lists
from baseballdata import baseball

# Import numpy package
import numpy as np

# Create a 2D numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

# Print out the type and shape of np_baseball
print(type(np_baseball), np_baseball.shape)

File ‘baseballdata.py’ already there; not retrieving.

<class 'numpy.ndarray'> (1015, 2)

### **Exercise 24**: Indexing 2D baseball

- Print the 50th line of the `np_baseball` 2D array
- Create `np_weight` containing the second column of `np_baseball`
- Print the shape of `np_weight` and make sure its one dimensional
- Print the height (first column) of the 100th player in `np_baseball`

In [ ]:
# download the baseball data
!wget -nc https://germain-forestier.info/dataset/baseballdata.py

# baseball is available as a regular list of lists
from baseballdata import baseball

# Import numpy package
import numpy as np

# Create np_baseball (2 cols)
np_baseball = np.array(baseball)

# Print out the 50th row of np_baseball

# Select the entire second column of np_baseball: np_weight , make sure its 1D

# Print out height of 100th player

 ### Solution - Exercise 24

In [ ]:
# download the baseball data
!wget -nc https://germain-forestier.info/dataset/baseballdata.py

# baseball is available as a regular list of lists
from baseballdata import baseball

# Import numpy package
import numpy as np

# Create np_baseball (2 cols)
np_baseball = np.array(baseball)

# Print out the 50th row of np_baseball
print(np_baseball[49])

# Select the entire second column of np_baseball: np_weight , make sure its 1D
np_weight = np_baseball[:,1]
print(np_weight.shape, len(np_weight.shape))

# Print out height of 100th player
print(np_baseball[99,0])

File ‘baseballdata.py’ already there; not retrieving.

[ 70 195]
(1015,) 1
74

### **Exercise 25**: Conversion by array multiplication

- After loading the `np_baseball`, a 2D array with height, weight and age of all baseball players, add the two arrays `np_baseball` and `updated` and print the results
- In order to conver the values to the correct units, create the array `conversions` containing the 3 values `0.0254`, `0.453592` and `1`
- Multiply `np_baseball` by `conversions` and print the results

In [ ]:
# download the baseball data
!wget -nc https://germain-forestier.info/dataset/baseballdata2.py

# updated is available as 2D numpy array
from baseballdata2 import baseball, updated

# Import numpy package
import numpy as np

# Create np_baseball (3 cols)
np_baseball = np.array(baseball)
print(np_baseball)

# Print out addition of np_baseball and updated

# Create numpy array: conversion

# Print out product of np_baseball and conversion

 ### Solution - Exercise 25

In [ ]:
# download the baseball data
!wget -nc https://germain-forestier.info/dataset/baseballdata2.py

# updated is available as 2D numpy array
from baseballdata2 import baseball, updated

# Import numpy package
import numpy as np

# Create np_baseball (3 cols)
np_baseball = np.array(baseball)
print(np_baseball)

# Print out addition of np_baseball and updated
print(np_baseball + updated)

# Create numpy array: conversion
conversions = np.array([0.0254, 0.453592, 1])

# Print out product of np_baseball and conversion
print(np_baseball * conversions)

File ‘baseballdata2.py’ already there; not retrieving.

[[ 74.   180.    22.99]
 [ 74.   215.    34.69]
 [ 72.   210.    30.78]
 ...
 [ 75.   205.    25.19]
 [ 75.   190.    31.01]
 [ 73.   195.    27.92]]
[[ 75.2303559  168.837751    23.99      ]
 [ 75.02614252 231.0973231   35.69      ]
 [ 73.1544228  215.08167641  31.78      ]
 ...
 [ 76.09349925 209.23890778  26.19      ]
 [ 75.82285669 172.2179997   32.01      ]
 [ 73.99484223 203.14402711  28.92      ]]
[[ 1.8796  81.64656 22.99   ]
 [ 1.8796  97.52228 34.69   ]
 [ 1.8288  95.25432 30.78   ]
 ...
 [ 1.905   92.98636 25.19   ]
 [ 1.905   86.18248 31.01   ]
 [ 1.8542  88.45044 27.92   ]]

### **Numpy statistics**

- To understand your data you can visualize it and print it simply
- What happens you have a lot of data ?

In [ ]:
import numpy as np
np_city = np.array([[ 1.64, 71.78],
                    [ 1.37, 63.35],
                    [ 1.6 , 55.09],
                    [ 2.04, 74.85],
                    [ 2.04, 68.72],
                    [ 2.01, 73.57]])
print(np.mean(np_city[:,0]))
print(np.median(np_city[:,0]))

print(np.corrcoef(np_city[:,0], np_city[:,1]))
print(np.std(np_city[:,0]))

1.7833333333333332
1.8249999999999997
[[1.         0.64924262]
 [0.64924262 1.        ]]
0.2608107018935807

### **Exercise 26**: Median and Mean

- Create the `np_height` the first column of `np_baseball`
- Print the mean of heights
- Print the median of heights
- Is there something you notice ?

In [ ]:
# donwload the baseball data
!wget -nc https://germain-forestier.info/dataset/baseballdata3.py

# np_baseball is available
from baseballdata3 import *

# Import numpy
import numpy as np

# Create np_height from np_baseball

# Print out the mean of np_height

# Print out the median of np_height

 ### Solution - Exercise 26

In [ ]:
# donwload the baseball data
!wget -nc https://germain-forestier.info/dataset/baseballdata3.py

# np_baseball is available
from baseballdata3 import *

# Import numpy
import numpy as np

# Create np_height from np_baseball
np_height = np_baseball[:,0]

# Print out the mean of np_height
print(np.mean(np_height))

# Print out the median of np_height
print(np.median(np_height))

File ‘baseballdata3.py’ already there; not retrieving.

1586.4610837438424
74.0
[7.4e+04 7.4e+01 7.2e+01 ... 7.5e+01 7.5e+01 7.3e+01]

### **Exercise 27**: Correlation

- Complete the following code to calculate the median and std of the first column of `np_baseball`
- Are the two features, height and weight, related ? use `np.corrcoef()` to find the correlation between the 2 first columns of `np_baseball`

In [ ]:
# download the baseball data
!wget -nc https://germain-forestier.info/dataset/baseballdata3.py

# np_baseball is available
from baseballdata3 import np_baseball

# Print mean height (first column)
avg = np.mean(np_baseball[:,0])
print("Average: " + str(avg))

# Print median height. Replace 'None'
med = None
print("Median: " + str(med))

# Print out the standard deviation on height. Replace 'None'
stddev = None
print("Standard Deviation: " + str(stddev))

# Print out correlation between first and second column. Replace 'None'
corr = None
print("Correlation: " + str(corr))

File ‘baseballdata3.py’ already there; not retrieving.

Average: 1586.4610837438424
Median: 74.0
Standard Deviation: 10409.724179620522
Correlation: [[1.         0.02776109]
 [0.02776109 1.        ]]

 ### Solution - Exercise 27

In [ ]:
# download the baseball data
!wget -nc https://germain-forestier.info/dataset/baseballdata3.py

# np_baseball is available
from baseballdata3 import np_baseball

# Print mean height (first column)
avg = np.mean(np_baseball[:,0])
print("Average: " + str(avg))

# Print median height. Replace 'None'
med = np.median(np_baseball[:,0])
print("Median: " + str(med))

# Print out the standard deviation on height. Replace 'None'
stddev = np.std(np_baseball[:,0])
print("Standard Deviation: " + str(stddev))

# Print out correlation between first and second column. Replace 'None'
corr = np.corrcoef(np_baseball[:,0], np_baseball[:,1])
print("Correlation: " + str(corr))

### **Exercise 28**: Indexing with string array

- Convert both `heights` and `positions` to numpy arrays
- Extract `gk_heights` from `np_heights` by indexing `np_positions == 'GK'`
- Extract `other_heights` from `np_heights` by indexing over the rest
- Print the median of both new arrays

In [ ]:
# donwload the football data
!wget -nc https://germain-forestier.info/dataset/foot.py

# heights and positions are available as lists
from foot import *

# Convert positions and heights to numpy arrays: np_positions, np_heights

# Heights of the goalkeepers: gk_heights

# Heights of the other players: other_heights

# Print out the median height of goalkeepers. Replace 'None'
print("Median height of goalkeepers: " + str(None))

# Print out the median height of other players. Replace 'None'
print("Median height of other players: " + str(None))

 ### Solution - Exercise 28

In [ ]:
# donwload the football data
!wget -nc https://germain-forestier.info/dataset/foot.py

# heights and positions are available as lists
from foot import heights, positions

# Convert positions and heights to numpy arrays: np_positions, np_heights
np_heights = np.array(heights)
np_positions = np.array(positions)

# Heights of the goalkeepers: gk_heights
gk_heights = np_heights[np_positions == 'GK']

# Heights of the other players: other_heights
other_heights = np_heights[np_positions != 'GK']

# Print out the median height of goalkeepers. Replace 'None'
print("Median height of goalkeepers: " + str(np.median(gk_heights)))

# Print out the median height of other players. Replace 'None'
print("Median height of other players: " + str(np.median(other_heights)))

File ‘foot.py’ already there; not retrieving.

Median height of goalkeepers: 188.0
Median height of other players: 181.0